### ISSUE TITLE
Cant install this package node-gyp build failure?

### ISSUE THREAD

**Issue by Ajaymamtora** [Beaglefoot/tree-sitter-awk#24]
The build step fails when installing this package through NPM. Please could you help?

Term output:

```
> tree-sitter-awk@0.7.1 install
> node-gyp-build

gyp info it worked if it ends with ok
gyp info using node-gyp@10.0.1
gyp info using node@21.7.1 | linux | x64
gyp info find Python using Python version 3.12.2 found at "/home/linuxbrew/.linuxbrew/opt/python@3.12/bin/python3.12"

gyp info spawn /home/linuxbrew/.linuxbrew/opt/python@3.12/bin/python3.12
gyp info spawn args [
gyp info spawn args '/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args 'binding.gyp',
gyp info spawn args '-f',
gyp info spawn args 'make',
gyp info spawn args '-I',
gyp info spawn args '/home/ajaym/tmp/tree-sitter-awk/build/config.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args '-I',
gyp info spawn args '/home/ajaym/.cache/node-gyp/21.7.1/include/node/common.gypi',
gyp info spawn args '-Dlibrary=shared_library',
gyp info spawn args '-Dvisibility=default',
gyp info spawn args '-Dnode_root_dir=/home/ajaym/.cache/node-gyp/21.7.1',
gyp info spawn args '-Dnode_gyp_dir=/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args '-Dnode_lib_file=/home/ajaym/.cache/node-gyp/21.7.1/<(target_arch)/node.lib',
gyp info spawn args '-Dmodule_root_dir=/home/ajaym/tmp/tree-sitter-awk',
gyp info spawn args '-Dnode_engine=v8',
gyp info spawn args '--depth=.',
gyp info spawn args '--no-parallel',
gyp info spawn args '--generator-output',
gyp info spawn args 'build',
gyp info spawn args '-Goutput_dir=.'
gyp info spawn args ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/home/ajaym/tmp/tree-sitter-awk/build'
  TOUCH Release/obj.target/node_modules/node-addon-api/node_addon_api_except.stamp
  CXX(target) Release/obj.target/tree_sitter_awk_binding/bindings/node/binding.o
make: g++-11: No such file or directory
make: *** [tree_sitter_awk_binding.target.mk:116: Release/obj.target/tree_sitter_awk_binding/bindings/node/binding.o] Error 127
make: Leaving directory '/home/ajaym/tmp/tree-sitter-awk/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:209:23)
gyp ERR! System Linux 6.8.1-arch1-1
gyp ERR! command "/home/linuxbrew/.linuxbrew/Cellar/node/21.7.1/bin/node" "/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ajaym/tmp/tree-sitter-awk
gyp ERR! node -v v21.7.1
gyp ERR! node-gyp -v v10.0.1
gyp ERR! not ok 
npm ERR! code 1
npm ERR! path /home/ajaym/tmp/tree-sitter-awk
npm ERR! command failed
npm ERR! command sh -c node-gyp-build

npm ERR! A complete log of this run can be found in: /home/ajaym/.npm/_logs/2024-03-23T17_59_37_386Z-debug-0.log

```

Npm log:
```
0 verbose cli /home/linuxbrew/.linuxbrew/Cellar/node/21.7.1/bin/node /home/linuxbrew/.linuxbrew/bin/npm
1 info using npm@10.5.0
2 info using node@v21.7.1
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/linuxbrew/.linuxbrew/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/ajaym/tmp/tree-sitter-awk/.npmrc Completed in 0ms
10 timing config:load:project Completed in 3ms
11 timing config:load:file:/home/ajaym/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/linuxbrew/.linuxbrew/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 9ms
17 timing npm:load:configload Completed in 9ms
18 timing config:load:flatten Completed in 2ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 1ms
21 verbose title npm i
22 verbose argv "i"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 1ms
25 verbose logfile logs-max:10 dir:/home/ajaym/.npm/_logs/2024-03-23T17_59_37_386Z-
26 verbose logfile /home/ajaym/.npm/_logs/2024-03-23T17_59_37_386Z-debug-0.log
27 timing npm:load:logFile Completed in 6ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 30ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 24ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 timing idealTree:#root Completed in 0ms
38 timing idealTree:buildDeps Completed in 2ms
39 timing idealTree:fixDepFlags Completed in 0ms
40 timing idealTree Completed in 28ms
41 timing arborist:ctor Completed in 0ms
42 timing reify:loadTrees Completed in 36ms
43 timing reify:diffTrees Completed in 2ms
44 silly reify moves {}
45 timing reify:retireShallow Completed in 1ms
46 timing reify:createSparse Completed in 0ms
47 timing reify:loadBundles Completed in 0ms
48 silly audit bulk request {
48 silly audit   'base64-js': [ '1.5.1' ],
48 silly audit   bl: [ '4.1.0' ],
48 silly audit   buffer: [ '5.7.1' ],
48 silly audit   chownr: [ '1.1.4' ],
48 silly audit   'end-of-stream': [ '1.4.4' ],
48 silly audit   execspawn: [ '1.0.1' ],
48 silly audit   'fs-constants': [ '1.0.0' ],
48 silly audit   ieee754: [ '1.2.1' ],
48 silly audit   inherits: [ '2.0.4' ],
48 silly audit   'lru-cache': [ '6.0.0' ],
48 silly audit   minimist: [ '1.2.8' ],
48 silly audit   'mkdirp-classic': [ '0.5.3' ],
48 silly audit   'node-abi': [ '3.56.0' ],
48 silly audit   'node-addon-api': [ '7.1.0' ],
48 silly audit   'node-gyp-build': [ '4.8.0' ],
48 silly audit   'npm-run-path': [ '3.1.0' ],
48 silly audit   once: [ '1.4.0' ],
48 silly audit   'path-key': [ '3.1.1' ],
48 silly audit   prebuildify: [ '6.0.0' ],
48 silly audit   prettier: [ '2.3.2' ],
48 silly audit   pump: [ '3.0.0' ],
48 silly audit   'readable-stream': [ '3.6.2' ],
48 silly audit   'safe-buffer': [ '5.2.1' ],
48 silly audit   semver: [ '7.6.0' ],
48 silly audit   string_decoder: [ '1.3.0' ],
48 silly audit   'tar-fs': [ '2.1.1' ],
48 silly audit   'tar-stream': [ '2.2.0' ],
48 silly audit   'tree-sitter': [ '0.21.0' ],
48 silly audit   'tree-sitter-cli': [ '0.22.1' ],
48 silly audit   'util-deprecate': [ '1.0.2' ],
48 silly audit   'util-extend': [ '1.0.3' ],
48 silly audit   wrappy: [ '1.0.2' ],
48 silly audit   yallist: [ '4.0.0' ]
48 silly audit }
49 timing reify:unpack Completed in 2ms
50 timing reify:unretire Completed in 12ms
51 timing build:queue Completed in 0ms
52 timing build:deps Completed in 0ms
53 timing build Completed in 0ms
54 timing reify:build Completed in 1ms
55 timing reify:trash Completed in 0ms
56 timing reify:save Completed in 27ms
57 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 302ms
58 timing auditReport:getReport Completed in 305ms
59 silly audit report {}
60 timing auditReport:init Completed in 0ms
61 timing reify:audit Completed in 306ms
62 timing reify Completed in 352ms
63 timing command:i Completed in 787ms
64 verbose stack Error: command failed
64 verbose stack     at ChildProcess.<anonymous> (/home/linuxbrew/.linuxbrew/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/lib/index.js:53:27)
64 verbose stack     at ChildProcess.emit (node:events:519:28)
64 verbose stack     at maybeClose (node:internal/child_process:1105:16)
64 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
65 verbose pkgid tree-sitter-awk@0.7.1
66 verbose cwd /home/ajaym/tmp/tree-sitter-awk
67 verbose Linux 6.8.1-arch1-1
68 verbose node v21.7.1
69 verbose npm  v10.5.0
70 error code 1
71 error path /home/ajaym/tmp/tree-sitter-awk
72 error command failed
73 error command sh -c node-gyp-build
74 verbose exit 1
75 timing npm Completed in 939ms
76 verbose code 1
77 error A complete log of this run can be found in: /home/ajaym/.npm/_logs/2024-03-23T17_59_37_386Z-debug-0.log
```

**Comment by Beaglefoot** [comment]
I believe here's the culprit:

> make: g++-11: No such file or directory

Check that g++ accessible on command-line and if not install it. On opensuse for example the package called gcc-c++.

**Comment by Beaglefoot** [comment]
What OS are you using?

**Comment by Beaglefoot** [comment]
I currently have no opportunity to try installation process on endeavouros, but I tried with arch image in docker container.

And tree-sitter-awk can be installed with npm after installing these 3 packages:
```
pacman -Sy --needed base-devel nodejs npm
```

Do you have `base-devel` installed?
